  Philip[m
  dev_main[m
  feat/admin[m
  feat/auth[m
  feat/community[m
  feat/cookie[m
  feat/course[m
  feat/dashboard[m
  feat/dashboard-my-activity[m
* [32mfeat/first-qa-partial[m
  feat/global-layout[m
  feat/inquiry_report[m
  feat/mainpage[m
  feat/notice[m
  feat/review-write-summary[m
  feat/support[m
  feature/ai-agent-connect[m
  main[m
  refactor/setup[m
  test[m
